### ISSUE TITLE
Saving a CK2 entry does nothing

### ISSUE THREAD

**Issue by NicolasGrosjean** [NicolasGrosjean/Translate_helper#33]
When translating this file, when we save the entry, it does nothing.

>#LAST EDIT: 29 November 2017 - Phaze49
################
#NORSCA EVENTS#
################
NAMEPSACE = whitewale
EVTDESCwhitewhale.100;You recieve news that a massive white whale has been sinking your whaling vessels and is disrupting your trade with the other Norscan tribes!;Vous recevez des informations à propos d'une immense baleine blanche qui coule vos navires baleiniers et interrompt votre commerce avec les autres tribus !;;;;;;;;;;;x
EVTDESCwhitewhale.101;Your men ready the longboats, loading them with spears and harpoons. Hopefully it will be enough to kill the beast.
EVTOPTAwhitewhale.101;We shall hunt the beast down! Ready the longboats!;Nous allons tuer la bête ! Préparez les drakkars !;;;;;;;;;;;x
EVTOPTBwhitewhale.102;Call back our remaining whaling vessels.;Rappeler nos baleiniers restants;;;;;;;;;;;x
EVTDESCwhitewhale.102;You send out word that all remaining whaling vessels are to return to the village immediately. Hopefully the beast will lose interest and wander off.;Vous ordonnez que tous les navires baleiniers rentrent au port immédiatement. Espérons que la bête s'en désintéresse et s'en aille dans d'autres eaux.;;;;;;;;;;;x
EVTDESCwhitewhale.201; You Set sail out onto the open ocean
EVTOPTAwhitewhale.201; Set sail
EVTDESCwhitewhale.202;
EVTOPTAwhitewhale.202;There is no honor in retreat.;Il n'y a pas d'honneur dans la retraite;;;;;;;;;;;x

**Comment by NicolasGrosjean** [comment]
> Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 2
        at parsing.CK2ParsedFile.getNextEntryToTranslateAndSave(CK2ParsedFile.java:150)
        at gui.TranslatorDialog.lambda$9(TranslatorDialog.java:296)
